# Generated by Django 5.0.6 on 2024-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='telefon_turu',
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='rol',
            field=models.CharField(default='BERBER', max_length=15),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='telefon_numarasi',
            field=models.CharField(max_length=11),
        ),
    ]
