# Generated by Django 5.0.6 on 2024-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0002_remove_kullanici_telefon_turu_alter_kullanici_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='soyad',
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
