# Generated by Django 5.0.6 on 2024-05-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0003_remove_kullanici_ad_remove_kullanici_soyad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
