# Generated by Django 5.0.6 on 2024-05-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0004_alter_kullanici_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='rol',
            field=models.CharField(default='MISAFIR', max_length=15),
        ),
    ]
