# Generated by Django 5.0.6 on 2024-05-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukkan',
            name='sahibi',
            field=models.ForeignKey(limit_choices_to={'rol': 'DUKKAN_SAHIBI'}, on_delete=django.db.models.deletion.CASCADE, related_name='dukkanlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
