# Generated by Django 5.0.6 on 2024-05-12 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0003_alter_dukkan_sahibi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dukkan',
            name='berberler',
            field=models.ManyToManyField(blank=True, related_name='calistigi_dukkanlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
