# Generated by Django 5.0.6 on 2024-05-15 18:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0004_dukkan_berberler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dukkan',
            name='acilis_saati',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
        migrations.AddField(
            model_name='dukkan',
            name='calisma_gunleri',
            field=models.CharField(blank=True, choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma'), ('Cumartesi', 'Cumartesi'), ('Pazar', 'Pazar')], default=['Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma'], max_length=255),
        ),
        migrations.AddField(
            model_name='dukkan',
            name='kapanis_saati',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='dukkan',
            name='sahibi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dukkanlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dukkan',
            name='telefon',
            field=models.CharField(max_length=11),
        ),
    ]
