# Generated by Django 5.0.6 on 2024-05-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0006_alter_dukkan_calisma_gunleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='dukkan',
            name='calisma_gunleri',
        ),
        migrations.AddField(
            model_name='dukkan',
            name='calisma_gunleri',
            field=models.ManyToManyField(blank=True, related_name='dukkanlar', to='dukkanlar.gun'),
        ),
    ]
