# Generated by Django 5.0.6 on 2024-05-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0007_gun_remove_dukkan_calisma_gunleri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dukkan',
            name='calisma_gunleri',
        ),
        migrations.DeleteModel(
            name='Gun',
        ),
        migrations.AddField(
            model_name='dukkan',
            name='calisma_gunleri',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Pazartesi'), ('TUESDAY', 'Salı'), ('WEDNESDAY', 'Çarşamba'), ('THURSDAY', 'Perşembe'), ('FRIDAY', 'Cuma'), ('SATURDAY', 'Cumartesi'), ('SUNDAY', 'Pazar')], default=['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'], max_length=255),
        ),
    ]
