# Generated by Django 5.0.6 on 2024-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0009_gun_remove_dukkan_calisma_gunleri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(db_index=True, max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(db_index=True, max_length=11, unique=True)),
                ('eposta', models.EmailField(blank=True, max_length=254)),
                ('dukkanlar', models.ManyToManyField(blank=True, related_name='musteriler', to='dukkanlar.dukkan')),
            ],
        ),
    ]
