# Generated by Django 5.0.6 on 2024-06-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0010_musteri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='telefon',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True),
        ),
    ]
