# Generated by Django 5.0.6 on 2024-05-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0004_dukkan_berberler'),
        ('randevular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musteri',
            name='dukkanlar',
            field=models.ManyToManyField(blank=True, related_name='musteriler', to='dukkanlar.dukkan'),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='ad',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='musteri',
            name='telefon',
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
    ]
