# Generated by Django 5.0.6 on 2024-05-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkanlar', '0010_musteri'),
        ('randevular', '0002_musteri_dukkanlar_alter_musteri_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukkanlar.musteri'),
        ),
        migrations.DeleteModel(
            name='Musteri',
        ),
    ]
